import type { Finding, Reporter, ReviewResult, Severity } from '@relay/shared';

const STATUS_ICONS: Record<string, string> = {
  ship: '✅',
  warn: '⚠️',
  hold: '❌',
  critical: '🚨',
};

const SEVERITY_EMOJI: Record<Severity, string> = {
  critical: '🔴',
  high: '🟠',
  medium: '🟡',
  low: '🔵',
  info: '⚪',
};

export class GithubReporter implements Reporter {
  name = 'github';

  render(result: ReviewResult): string {
    const lines: string[] = [];

    // Title
    const statusIcon = STATUS_ICONS[result.status] ?? '❓';
    const statusLabel = result.status.toUpperCase();
    lines.push(`## ${statusIcon} Relay Code Quality Review — **${statusLabel}**`);
    lines.push('');
    lines.push(
      `**Score:** \`${result.score}/100\` | **Framework:** \`${result.framework}\` | **Rules Checked:** \`${result.rulesRun}\``
    );
    lines.push('');
    lines.push('---');
    lines.push('');

    // Category Table
    lines.push('### 📊 Category Summary');
    lines.push('');
    lines.push('| Category | Score | Findings | Status |');
    lines.push('| :--- | :--- | :--- | :--- |');
    for (const cat of result.categoryScores) {
      const catIcon = cat.status === 'pass' ? '✅' : cat.status === 'warn' ? '⚠️' : '❌';
      lines.push(
        `| **${cat.category}** | ${cat.score}/${cat.maxScore} | ${cat.findingCount} | ${catIcon} ${cat.status} |`
      );
    }
    lines.push('');

    // Group findings by severity
    const critical = result.findings.filter((f) => f.severity === 'critical');
    const high = result.findings.filter((f) => f.severity === 'high');
    const rest = result.findings.filter((f) => ['medium', 'low', 'info'].includes(f.severity));

    if (critical.length > 0) {
      lines.push('### 🚨 Critical Issues');
      lines.push('');
      for (const f of critical) {
        this.renderFindingLine(lines, f);
      }
      lines.push('');
    }

    if (high.length > 0) {
      lines.push('### 🟠 High Priority Issues');
      lines.push('');
      for (const f of high) {
        this.renderFindingLine(lines, f);
      }
      lines.push('');
    }

    if (rest.length > 0) {
      lines.push('<details>');
      lines.push(
        `<summary><b>🔍 View Medium & Low Priority Findings (${rest.length})</b></summary>`
      );
      lines.push('');
      for (const f of rest) {
        this.renderFindingLine(lines, f);
      }
      lines.push('</details>');
      lines.push('');
    }

    if (result.findings.length === 0) {
      lines.push('🎉 **No issues found!** Your code changes are clean and look excellent.');
      lines.push('');
    }

    lines.push('---');
    lines.push('*Report generated by [Relay](https://github.com/relay-dev/relay)*');

    return lines.join('\n');
  }

  private renderFindingLine(lines: string[], f: Finding): void {
    const emoji = SEVERITY_EMOJI[f.severity] ?? '⚪';
    const loc = f.file ? (f.line ? `\`${f.file}#L${f.line}\`` : `\`${f.file}\``) : '';
    lines.push(`- ${emoji} **${f.ruleId}**: ${f.message} ${loc ? `in ${loc}` : ''}`);
    if (f.evidence) {
      lines.push(`  - *Evidence:* \`${f.evidence.replace(/`/g, '\\`').trim()}\``);
    }
    if (f.suggestion) {
      lines.push(`  - *Fix:* ${f.suggestion}`);
    }
  }
}
