import type { Finding, Reporter, ReviewResult, Severity } from '@relay/shared';

const STATUS_EMOJI: Record<string, string> = {
  ship: '✅',
  warn: '⚠️',
  hold: '❌',
  critical: '🚨',
};

const SEVERITY_EMOJI: Record<Severity, string> = {
  critical: '🔴',
  high: '🟠',
  medium: '🟡',
  low: '🔵',
  info: '⚪',
};

export class MarkdownReporter implements Reporter {
  name = 'markdown';

  render(result: ReviewResult): string {
    const lines: string[] = [];
    const { status, score, framework, timestamp } = result;
    const emoji = STATUS_EMOJI[status] ?? '?';

    lines.push(`# ${emoji} Relay Review Report`);
    lines.push('');
    lines.push(`**Generated:** ${new Date(timestamp).toLocaleString()}  `);
    lines.push(`**Framework:** ${framework}  `);
    lines.push(`**Score:** ${score}/100  `);
    lines.push(`**Status:** \`${status.toUpperCase()}\`  `);
    lines.push('');
    lines.push('---');
    lines.push('');

    // Category scores
    if (result.categoryScores.length > 0) {
      lines.push('## Category Scores');
      lines.push('');
      lines.push('| Category | Score | Findings | Status |');
      lines.push('|----------|-------|----------|--------|');
      for (const cat of result.categoryScores) {
        const icon = cat.status === 'pass' ? '✅' : cat.status === 'warn' ? '⚠️' : '❌';
        lines.push(
          `| ${cat.category} | ${cat.score}/${cat.maxScore} | ${cat.findingCount} | ${icon} ${cat.status} |`
        );
      }
      lines.push('');
    }

    // Findings grouped by severity
    const severities: Severity[] = ['critical', 'high', 'medium', 'low', 'info'];
    for (const severity of severities) {
      const findings = result.findings.filter((f) => f.severity === severity);
      if (findings.length === 0) continue;

      const title = severity.charAt(0).toUpperCase() + severity.slice(1);
      lines.push(`## ${SEVERITY_EMOJI[severity]} ${title} Issues (${findings.length})`);
      lines.push('');

      for (const finding of findings) {
        this.renderFinding(lines, finding);
      }
    }

    // Summary
    lines.push('---');
    lines.push('');
    lines.push('## Summary');
    lines.push('');
    const s = result.summary;
    lines.push('| Severity | Count |');
    lines.push('|----------|-------|');
    if (s.critical > 0) lines.push(`| 🔴 Critical | ${s.critical} |`);
    if (s.high > 0) lines.push(`| 🟠 High | ${s.high} |`);
    if (s.medium > 0) lines.push(`| 🟡 Medium | ${s.medium} |`);
    if (s.low > 0) lines.push(`| 🔵 Low | ${s.low} |`);
    if (s.info > 0) lines.push(`| ⚪ Info | ${s.info} |`);
    lines.push(`| **Total** | **${s.total}** |`);
    lines.push('');
    lines.push('---');
    lines.push('');
    lines.push(`*Generated by [Relay](https://github.com/relay-dev/relay) v${result.version}*`);
    lines.push('');

    return lines.join('\n');
  }

  private renderFinding(lines: string[], finding: Finding): void {
    const loc = finding.file
      ? finding.line
        ? `\`${finding.file}:${finding.line}\``
        : `\`${finding.file}\``
      : null;

    lines.push(`### \`${finding.ruleId}\` — ${finding.message}`);
    lines.push('');
    if (loc) lines.push(`**Location:** ${loc}  `);
    if (finding.evidence) lines.push(`**Evidence:** \`${finding.evidence}\`  `);
    if (finding.suggestion) lines.push(`**Suggestion:** ${finding.suggestion}  `);
    if (finding.docs) lines.push(`**Docs:** ${finding.docs}  `);
    lines.push('');
  }
}
